# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

!pip install bert-extractive-summarizer

from summarizer import Summarizer

model = Summarizer()

from google.colab import files
uploaded = files.upload()
for filename in uploaded.keys():
    # Open and read the uploaded text file
    with open(filename, "r", encoding="utf-8") as file:
        text = file.read()

summary = model(text, ratio=0.9)
print(summary)

from transformers import pipeline

qa_pipeline = pipeline("question-answering", model="bert-large-uncased-whole-word-masking-finetuned-squad")



question = "Who is the tesla CEO? "

result = qa_pipeline(question=question, context=text)
print(f"Answer: {result['answer']}")